//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ev3
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSocios
    {
        public int ID { get; set; }
        public string Rut { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int Telefono { get; set; }
        public string Email { get; set; }
        public int Edad { get; set; }
        public double Estatura { get; set; }
        public int Peso { get; set; }
    }
}
